name: Build
'on':
  repository_dispatch:
    types:
      - run
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: fffaddcddfbeddefbfbffeebcabbefbeddbea
          SONAR_TOKEN: sqa_bca47d55147cb1b256a213a17c135dfe863be411
          SONAR_HOST_URL: 'https://sonar.server.examly.io'
      - name: Trigger API
        if: always()
        env:
          API_URL: '${{ secrets.API_URL }}'
          API_SECRET: '${{ secrets.API_SECRET }}'
        run: >
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          API_PAYLOAD="{ \"repo_id\": \"$REPO_NAME\", \"branch_name\":
          \"$BRANCH_NAME\", \"api_secret\": \"$API_SECRET\" }"

          curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD"
          $API_URL
